### PR TITLE
Various wayland fixes

### PR DESCRIPTION
**Pull request by smspillaz**
This PR includes various fixes for wayland, including fixes to get the test-suite working again.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
What is the advantage of an anonymous namespace?

**Comment by smspillaz** [comment]
@MaxKellermann For me personally, its mostly a stylistic and consistency thing. There's some reasons as to why you might want to use it at this link: http://stackoverflow.com/questions/4977252/why-unnamed-namespace-is-a-superior-alternative-to-static .

**Comment by MaxKellermann** [comment]
Merged. Note that I rebase on upstream/master often, so I'll force-push my master branch each time.

**Comment by smspillaz** [comment]
No worries :)

**Pull request merged**
